###
GET http://localhost:5000

# PRODUCT API

###
GET http://localhost:5000/product

###
POST http://localhost:5000/product
Content-Type: application/json

{
    "name" : "/128Gb/256Gb Garansi Resmi IBOX/TAM - Hitam, 64Gb",
    "price" : "11.340",
    "category" : 1
}

###
PUT  http://localhost:5000/product/6
Content-Type: application/json

{
    "name" : "Ip 13 64Gb/128Gb/256Gb Garansi Resmi IBOX/TAM - Hitam, 64Gb",
    "price" : "11.341",
    "category" : 5
}

###
DELETE  http://localhost:5000/product/6


# PRODUCT ASSETS API

###
GET http://localhost:5000/assets

###
POST http://localhost:5000/assets
Content-Type: application/json

{
    "image" : "h111 Headset-stereo-single-jack 3,5mm.png",
    "productId" : 2
}

###
PUT  http://localhost:5000/assets/2
Content-Type: application/json

{
    "image" : "samsung 2 h111 Headset-stereo-single-jack 3,5mm.png",
    "productId" : 5
}

###
DELETE  http://localhost:5000/assets/4
