###
GET http://localhost:5000

# PRODUCT LOCAL API

###
GET http://localhost:5000/products

###
GET http://localhost:5000/products/detail

### with sorting
GET http://localhost:5000/products/price=DESC

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name" : "/128Gb/256Gb Garansi Resmi IBOX/TAM - Hitam, 64Gb",
    "price" : "11.000",
    "category" : 1
}

###
PUT  http://localhost:5000/products/6
Content-Type: application/json

{
    "name" : "Ip 13 64Gb/128Gb/256Gb Garansi Resmi IBOX/TAM - Hitam, 64Gb",
    "price" : "11.341",
    "category" : 5
}

###
DELETE  http://localhost:5000/products/6


# PRODUCT ASSETS LOCAL API

###
GET http://localhost:5000/assets

###
GET http://localhost:5000/assets/detail

###
POST http://localhost:5000/assets
Content-Type: application/json

{
    "image" : "h111 Headset-stereo-single-jack 3,5mm.png",
    "productId" : 3
}

###
PUT  http://localhost:5000/assets/2
Content-Type: application/json

{
    "image" : "samsung 2 h111 Headset-stereo-single-jack 3,5mm.png",
    "productId" : 5
}

###
DELETE  http://localhost:5000/assets/41


# CATEGORIES LOCAL API

###
GET http://localhost:5000/categories

###
POST http://localhost:5000/categories
Content-Type: application/json

{
    "name" : "Sports"
}

###
PUT  http://localhost:5000/categories/6
Content-Type: application/json

{
    "name" : "Calistechnique"
}

###
DELETE  http://localhost:5000/categories/6
